# Generated by Django 5.2.3 on 2025-09-05 12:05

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=finance.models.next_po_number, editable=False, max_length=20, unique=True),
        ),
    ]
