# Generated by Django 5.2.3 on 2025-09-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('SALARIES', 'Salaries'), ('SUPPLIES', 'Supplies'), ('MAINTENANCE', 'Maintenance'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.purchaseorder'),
        ),
    ]
