# Generated by Django 5.2.3 on 2025-09-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_category_expense_purchase_order'),
        ('hr', '0002_alter_salaryrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together={('salary_record', 'treasury', 'date')},
        ),
    ]
