# Generated by Django 5.2.3 on 2025-09-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_salarypayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='salarypayment',
            unique_together=set(),
        ),
    ]
