# Generated by Django 5.2.3 on 2025-09-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-month']},
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('staff', 'month')},
        ),
    ]
