# Generated by Django 5.2.3 on 2025-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('PNL', 'Profit & Loss'), ('BS', 'Balance Sheet'), ('CASH', 'Cash Flow'), ('PAYROLL_VS_ATT', 'Payroll vs Attendance'), ('LOW_STOCK', 'Low Stock')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('file', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
