# Generated by Django 5.2.3 on 2025-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportjob',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='reportjob',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('PNL', 'Profit & Loss'), ('BS', 'Balance Sheet'), ('CASH', 'Cash Flow'), ('PAYROLL_VS_ATT', 'Payroll vs Attendance'), ('LOW_STOCK', 'Low Stock'), ('DOC_EXP', 'Expiring Documents')], max_length=30),
        ),
    ]
