# Generated by Django 5.2.3 on 2025-08-19 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reportjob_options_reportjob_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reportjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reportjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('PNL', 'Profit & Loss'), ('BS', 'Balance Sheet'), ('CASH', 'Cash Flow'), ('PAYROLL_VS_ATT', 'Payroll vs Attendance (Excel)'), ('LOW_STOCK', 'Low Stock (Excel)'), ('DOC_EXP', 'Expiring Documents (Excel)'), ('STUDENT_DOCS', 'Student Documents (PDF)'), ('LOW_STOCK_PDF', 'Low Stock (PDF)'), ('STUDENT_FEES', 'Student Fees Status'), ('ENROLL_SUMMARY', 'Enrollment Summary')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
