# Generated by Django 5.2.3 on 2025-08-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_reportjob_options_remove_reportjob_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('PNL', 'Profit & Loss'), ('BS', 'Balance Sheet'), ('CASH', 'Cash Flow'), ('PAYROLL_VS_ATT', 'Payroll vs Attendance (Excel)'), ('LOW_STOCK', 'Low Stock (Excel)'), ('DOC_EXP', 'Expiring Documents (Excel)'), ('STUDENT_DOCS', 'Student Documents (PDF)'), ('LOW_STOCK_PDF', 'Low Stock (PDF)'), ('STUDENT_FEES', 'Student Fees Status'), ('ENROLL_SUMMARY', 'Enrollment Summary'), ('AR_AGING', 'Accounts Receivable Aging'), ('AP_AGING', 'Accounts Payable Aging'), ('INV_VALUATION', 'Inventory Valuation'), ('HR_ATT_SUMMARY', 'HR Attendance Summary')], max_length=40),
        ),
    ]
