# Generated by Django 5.2.3 on 2025-06-27 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyassignment',
            name='assigned_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
