# Generated by Django 5.2.3 on 2025-06-27 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('inventory', '0002_alter_custodyassignment_assigned_on_and_more'),
        ('student', '0008_medicalrecord_conducted_by_medicalrecord_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktake',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='responsible_staff',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_required',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Min Stock Level'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('UNIFORM', 'Uniform'), ('BOOK', 'Book'), ('EQUIPMENT', 'Equipment'), ('STATIONERY', 'Stationery'), ('ASSET', 'Asset')], max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('handed_over_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('FULL', 'Fully Handed Over'), ('PARTIAL', 'Partially Handed Over'), ('PENDING', 'Pending Delivery')], default='PENDING', max_length=10)),
                ('assigned_on', models.DateField(default=django.utils.timezone.now)),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomatedReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_level', models.PositiveIntegerField()),
                ('order_quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('AUDIT', 'Audit Adjustment'), ('RESTOCK', 'Restock'), ('ASSIGN', 'Assignment'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustodyAssignment',
        ),
        migrations.DeleteModel(
            name='StockTake',
        ),
    ]
