# Generated by Django 5.2.3 on 2025-06-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('inventory', '0004_remove_assignment_created_at_and_more'),
        ('student', '0008_medicalrecord_conducted_by_medicalrecord_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedreorderrule',
            name='item',
        ),
        migrations.RemoveField(
            model_name='automatedreorderrule',
            name='preferred_vendor',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_stock',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='item',
            name='min_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('UNIFORM', 'Uniform'), ('BOOK', 'Book'), ('EQUIP', 'Equipment'), ('TOY', 'Toy'), ('ASSET', 'Asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CustodyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('assigned_on', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('counted_quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('responsible_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AutomatedReorderRule',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
