# Generated by Django 5.2.3 on 2025-06-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID / Passport'), ('Parents Doc', 'Parents Doc')], max_length=20),
        ),
    ]
