# Generated by Django 5.2.3 on 2025-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_gender_alter_studentdocument_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id_expiry',
            new_name='parent_id_expiry',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_number',
            new_name='parent_id_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_id_number',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID / Passport'), ('Parents Doc', 'Parents D')], max_length=20),
        ),
    ]
