# Generated by Django 5.2.3 on 2025-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_id_expiry_student_parent_id_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID / Passport'), ('Parents Doc', 'Parents Doc')], max_length=20),
        ),
    ]
