# Generated by Django 5.2.3 on 2025-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('LEFT', 'Left'), ('SHIFTED', 'Shifted from another school')], default='ACTIVE', max_length=10),
        ),
    ]
