# Generated by Django 5.2.3 on 2025-06-27 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_evaluation_notes_evaluation_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='conducted_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conducted By'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Record Date'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doctor/Clinic Name'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent Attention Needed'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Checkup Due'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Health Program Name'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('ALLERGY', 'Allergy'), ('MEDICATION', 'Medication'), ('TREATMENT', 'Treatment'), ('VACCINATION', 'Vaccination'), ('CHECKUP', 'Periodic Checkup'), ('DOCTOR_NOTE', 'Doctor’s Notes'), ('EDUCATION', 'Health Education')], max_length=20),
        ),
    ]
