# Generated by Django 5.2.3 on 2025-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_medicalrecord_conducted_by_medicalrecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('left', 'Left'), ('shifted', 'Shifted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
