# Generated by Django 5.2.3 on 2025-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_end_date_student_enrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('left', 'Left'), ('shifted', 'Shifted'), ('nonactive', 'nonactive')], default='active', max_length=20),
        ),
    ]
