# Generated by Django 5.2.3 on 2025-08-05 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('left', 'Left'), ('shifted', 'Shifted'), ('nonactive', 'Non-Active')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID / Passport'), ('PARENTS_DOC', 'Parents Doc'), ('SCHOOL_CERT', 'School Cert')], max_length=20),
        ),
    ]
