# Generated by Django 5.2.3 on 2025-08-05 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_attendance_date_alter_classroom_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='conducted_by',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='next_checkup_date',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('LEFT', 'Left')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='improvement_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('ALLERGY', 'Allergy'), ('MEDICATION', 'Medication'), ('VACCINATION', 'Vaccination')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID / Passport')], max_length=20),
        ),
    ]
