# Generated by Django 5.2.3 on 2025-08-05 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_medicalrecord_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('BIRTH_CERT', 'Birth Certificate'), ('ID', 'ID Card'), ('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('RESIDENCE', 'Residence Permit'), ('VACCINE', 'Vaccination Record'), ('TRANSCRIPT', 'Academic Transcript'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='file',
            field=models.FileField(upload_to='student_docs/%Y/%m/%d/'),
        ),
    ]
