# Generated by Django 5.2.3 on 2025-08-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_studentdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
