# Generated by Django 5.2.3 on 2025-08-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_guardian_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='conducted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('ALLERGY', 'Allergy'), ('MEDICATION', 'Medication'), ('TREATMENT', 'Treatment'), ('VACCINATION', 'Vaccination'), ('CHECKUP', 'Checkup'), ('DOCTOR_NOTE', "Doctor's Note"), ('EDUCATION', 'Health Education')], max_length=20),
        ),
    ]
