# Generated by Django 5.2.3 on 2025-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_medicalrecord_conducted_by_medicalrecord_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
