# Generated by Django 5.2.3 on 2025-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_student_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
